spring.application.name=backend
server.port=8081

# ===============================
# CONFIGURAÇÕES DO MYSQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=n${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURAÇÕES DO HIBERNATE/JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Chaves de API e Segurança
openai.api.key=${API_KEY}
jwt.secret=${JWT_SECRET}